### PR TITLE
correcting machine_head_with_fans_polygon dimensions for Neptune 4 Max

### PR DESCRIPTION
**Pull request by joelmdev**
# Description
 
correcting machine_head_with_fans_polygon dimensions for Neptune 4 Max. These come directly from the definition file in the Elegoo Cura 4.8 variant.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Printer definition file(s)

# How Has This Been Tested?

I've tested this on my personal N4M printer with Cura 5.6

### CODE REVIEW

**Comment by mastercaution** [comment]
Thank you for the PR and sorry for the wait.

Is the print head in the N4 Max different from the N4 and N4 Pro? On pictures and videos it looks identical. Did you measure the print head yourself as well to verify the values?

The values in the N4 definition file are measured by myself. Elegoo's previous profiles had values that were way off. My measurements are (always starting from the tip of the nozzle):
- 40mm to the left and right
- 30mm to the back
- 50mm to the front

[Documentation for `machine_head_with_fans_polygon`](https://github.com/Ghostkeeper/SettingsGuide/blob/master/resources/articles/machine_settings/machine_head_with_fans_polygon.md)

**Comment by joelmdev** [comment]
No worries here.

The extruders for the 4, and 4P/4M are different skus and I believe they have slightly different dimensions, but perhaps it's just nozzle? I don't have a standard/pro 4 to compare it to. I pulled the measurements directly from the Elegoo profile for the N4M. I believe this setting only comes into play if "one at a time" is selected as the print sequence setting. With the huge auxiliary fan installed it's nearly meaningless, it's just something I noticed as being different from Elegoo's official profile when moving things over.

**Comment by mastercaution** [comment]
I actually like to print things in "one at a time" mode, so I tried to get the measurements right. Print front parts first when the auxiliary fan is installed like this:

https://github.com/mastercaution/Cura/assets/16451370/da3456f3-5586-40e3-9b6f-11bf465d6fb7

**Comment by mastercaution** [comment]
The values from Elegoo doesn't make sense to me. As you can see in the pictures below, the polygon you proposed is smaller and has the wrong proportions. In pictures and videos, the print head looks exactly the same compared to the N4, so at least the proportions should match.

With "proportions" I mean that the nozzle is in the back half of the print head, so the the no-printing-area should be larger in the front. Let's look at these examples.

__Proposed polygon:__
Screenshot from 2024-01-12 13-23-01

__Current polygon:__
Screenshot from 2024-01-12 13-25-38

The current polygon is very close to the shape of the print head. Therefore, I'll ceep the current values also for the Plus and Max variant.

**Comment by mastercaution** [comment]
These are my measurements:

N4_print_head_measurements

**Pull request closed without merging**
